[package]
name = "particle-life"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ['cdylib']

[dependencies]
wasm-bindgen = "0.2.82"
web-sys = { version = "0.3.59", features = ["CanvasRenderingContext2d"]}
js-sys = "0.3.59"
serde_json = "1.0.75"